from django.core.management.base import BaseCommand
from nutrition.models import Food
from medical.models import Disease

class Command(BaseCommand):
    help = 'Seed database with Nepali foods and disease data'
    
    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding Nepali foods...')
        self.seed_foods()
        
        self.stdout.write('Seeding disease data...')
        self.seed_diseases()
        
        self.stdout.write(self.style.SUCCESS('Successfully seeded database!'))
    
    def seed_foods(self):
        foods_data = [
            {
                'name': 'Dal (Lentils)',
                'name_nepali': 'दाल',
                'category': 'protein',
                'season': 'all',
                'calories': 116,
                'protein': 9.0,
                'carbohydrates': 20.0,
                'fat': 0.4,
                'fiber': 8.0,
                'iron': 3.3,
                'health_benefits': 'High in protein and fiber, good for heart health',
                'suitable_for': 'diabetes, heart disease, weight management',
            },
            {
                'name': 'Brown Rice (Bhat)',
                'name_nepali': 'भात',
                'category': 'grain',
                'season': 'all',
                'calories': 112,
                'protein': 2.6,
                'carbohydrates': 23.5,
                'fat': 0.9,
                'fiber': 1.8,
                'health_benefits': 'Whole grain, rich in fiber and minerals',
                'suitable_for': 'general health, weight management',
            },
            {
                'name': 'Spinach (Palungo)',
                'name_nepali': 'पालुङ्गो',
                'category': 'vegetable',
                'season': 'winter',
                'calories': 23,
                'protein': 2.9,
                'carbohydrates': 3.6,
                'fat': 0.4,
                'fiber': 2.2,
                'vitamin_a': 469,
                'vitamin_c': 28,
                'iron': 2.7,
                'calcium': 99,
                'health_benefits': 'Rich in iron and vitamins, excellent for anemia',
                'suitable_for': 'anemia, eye health, bone health',
            },
            {
                'name': 'Mustard Greens (Rayo Saag)',
                'name_nepali': 'रायोसाग',
                'category': 'vegetable',
                'season': 'winter',
                'calories': 27,
                'protein': 2.7,
                'carbohydrates': 4.7,
                'fat': 0.2,
                'fiber': 3.2,
                'vitamin_a': 151,
                'vitamin_c': 70,
                'calcium': 103,
                'health_benefits': 'High in vitamins and antioxidants',
                'suitable_for': 'heart health, immunity, bone health',
            },
            {
                'name': 'Chicken',
                'name_nepali': 'कुखुराको मासु',
                'category': 'protein',
                'season': 'all',
                'calories': 165,
                'protein': 31.0,
                'carbohydrates': 0,
                'fat': 3.6,
                'iron': 0.9,
                'health_benefits': 'Lean protein source, good for muscle building',
                'suitable_for': 'weight management, muscle building, general health',
            },
            {
                'name': 'Tomato (Golbheda)',
                'name_nepali': 'गोलभेडा',
                'category': 'vegetable',
                'season': 'summer',
                'calories': 18,
                'protein': 0.9,
                'carbohydrates': 3.9,
                'fat': 0.2,
                'fiber': 1.2,
                'vitamin_c': 13.7,
                'health_benefits': 'Rich in lycopene and antioxidants',
                'suitable_for': 'heart health, cancer prevention',
            },
            {
                'name': 'Cucumber (Kakro)',
                'name_nepali': 'काक्रो',
                'category': 'vegetable',
                'season': 'summer',
                'calories': 15,
                'protein': 0.7,
                'carbohydrates': 3.6,
                'fat': 0.1,
                'fiber': 0.5,
                'vitamin_c': 2.8,
                'health_benefits': 'Hydrating, low calorie, good for skin',
                'suitable_for': 'weight loss, hydration, skin health',
            },
            {
                'name': 'Banana (Kera)',
                'name_nepali': 'केरा',
                'category': 'fruit',
                'season': 'all',
                'calories': 89,
                'protein': 1.1,
                'carbohydrates': 22.8,
                'fat': 0.3,
                'fiber': 2.6,
                'vitamin_c': 8.7,
                'health_benefits': 'Quick energy, rich in potassium',
                'suitable_for': 'hypertension, energy boost, digestion',
            },
            {
                'name': 'Mango (Aap)',
                'name_nepali': 'आँप',
                'category': 'fruit',
                'season': 'summer',
                'calories': 60,
                'protein': 0.8,
                'carbohydrates': 15.0,
                'fat': 0.4,
                'fiber': 1.6,
                'vitamin_a': 54,
                'vitamin_c': 36.4,
                'health_benefits': 'Rich in vitamins A and C, boosts immunity',
                'suitable_for': 'immunity, eye health, skin health',
            },
            {
                'name': 'Yogurt (Dahi)',
                'name_nepali': 'दही',
                'category': 'dairy',
                'season': 'all',
                'calories': 59,
                'protein': 3.5,
                'carbohydrates': 4.7,
                'fat': 3.3,
                'calcium': 121,
                'health_benefits': 'Probiotic, good for digestion and gut health',
                'suitable_for': 'digestion, bone health, immunity',
            },
            {
                'name': 'Almonds (Badam)',
                'name_nepali': 'बदाम',
                'category': 'nuts',
                'season': 'all',
                'calories': 579,
                'protein': 21.2,
                'carbohydrates': 21.6,
                'fat': 49.9,
                'fiber': 12.5,
                'vitamin_a': 0.3,
                'calcium': 269,
                'iron': 3.7,
                'health_benefits': 'Heart healthy fats, protein rich',
                'suitable_for': 'heart health, brain health, weight management',
            },
            {
                'name': 'Pumpkin (Farsi)',
                'name_nepali': 'फर्सी',
                'category': 'vegetable',
                'season': 'autumn',
                'calories': 26,
                'protein': 1.0,
                'carbohydrates': 6.5,
                'fat': 0.1,
                'fiber': 0.5,
                'vitamin_a': 426,
                'health_benefits': 'High in beta-carotene, good for eye health',
                'suitable_for': 'eye health, immunity, weight management',
            },
            {
                'name': 'Bitter Gourd (Karela)',
                'name_nepali': 'तितो करेला',
                'category': 'vegetable',
                'season': 'summer',
                'calories': 17,
                'protein': 1.0,
                'carbohydrates': 3.7,
                'fat': 0.2,
                'fiber': 2.8,
                'vitamin_c': 84,
                'health_benefits': 'Excellent for blood sugar control',
                'suitable_for': 'diabetes, blood sugar management',
            },
            {
                'name': 'Cauliflower (Kauli)',
                'name_nepali': 'काउली',
                'category': 'vegetable',
                'season': 'winter',
                'calories': 25,
                'protein': 1.9,
                'carbohydrates': 5.0,
                'fat': 0.3,
                'fiber': 2.0,
                'vitamin_c': 48.2,
                'health_benefits': 'Low calorie, high fiber, anti-inflammatory',
                'suitable_for': 'weight loss, heart health, digestion',
            },
            {
                'name': 'Carrot (Gajar)',
                'name_nepali': 'गाजर',
                'category': 'vegetable',
                'season': 'winter',
                'calories': 41,
                'protein': 0.9,
                'carbohydrates': 9.6,
                'fat': 0.2,
                'fiber': 2.8,
                'vitamin_a': 835,
                'health_benefits': 'Excellent source of beta-carotene',
                'suitable_for': 'eye health, skin health, immunity',
            },
        ]
        
        for food_data in foods_data:
            Food.objects.get_or_create(
                name=food_data['name'],
                defaults=food_data
            )
        
        self.stdout.write(f'Added {len(foods_data)} foods')
    
    def seed_diseases(self):
        diseases_data = [
            {
                'name': 'diabetes',
                'description': 'A metabolic disorder characterized by high blood sugar levels.',
                'category': 'metabolic',
                'severity': 'moderate',
                'dietary_guidelines': 'Focus on low glycemic index foods, high fiber, and balanced meals.',
                'foods_to_include': 'Whole grains, vegetables, legumes, nuts, lean proteins',
                'foods_to_avoid': 'Refined sugar, white bread, sugary drinks, processed foods',
            },
            {
                'name': 'hypertension',
                'description': 'High blood pressure condition affecting cardiovascular health.',
                'category': 'cardiovascular',
                'severity': 'moderate',
                'dietary_guidelines': 'Reduce sodium intake, increase potassium-rich foods.',
                'foods_to_include': 'Fruits, vegetables, whole grains, lean proteins, nuts',
                'foods_to_avoid': 'High sodium foods, processed meats, canned foods, pickles',
            },
            {
                'name': 'anemia',
                'description': 'Condition characterized by lack of healthy red blood cells.',
                'category': 'nutritional',
                'severity': 'mild',
                'dietary_guidelines': 'Increase iron-rich foods and vitamin C for better absorption.',
                'foods_to_include': 'Spinach, lentils, meat, fortified cereals, citrus fruits',
                'foods_to_avoid': 'Excessive tea/coffee with meals (inhibits iron absorption)',
            },
            {
                'name': 'obesity',
                'description': 'Excess body fat that may impair health.',
                'category': 'metabolic',
                'severity': 'moderate',
                'dietary_guidelines': 'Calorie deficit, high protein, high fiber, regular meals.',
                'foods_to_include': 'Vegetables, fruits, lean proteins, whole grains, water',
                'foods_to_avoid': 'Fast food, sugary drinks, refined carbs, excessive fats',
            },
            {
                'name': 'cholesterol',
                'description': 'High levels of cholesterol in the blood.',
                'category': 'cardiovascular',
                'severity': 'moderate',
                'dietary_guidelines': 'Reduce saturated fats, increase omega-3 and fiber.',
                'foods_to_include': 'Oats, nuts, fish, vegetables, fruits, olive oil',
                'foods_to_avoid': 'Fried foods, red meat, full-fat dairy, trans fats',
            },
        ]
        
        for disease_data in diseases_data:
            Disease.objects.get_or_create(
                name=disease_data['name'],
                defaults=disease_data
            )
        
        self.stdout.write(f'Added {len(diseases_data)} diseases')